### ISSUE TITLE
WorldWideAuction | サンクスページ作成

### ISSUE THREAD

**Issue by TAKUOO** [TAKUOO/rubydesign_works#24]
サイトのフォーム送信後のサンクスページの作成。

「Monobank worldwide auction へエントリーいただき、誠にありがとうございました。
自動返信メールにて入会申込書が送信されますので、ご記入（ご入力）のうえMAILかFAXにてご送信ください。
※古物許可書の添付が必要です。」
↓
ホームに戻るボタン

ぐらいでよいかなと思ってます。

#### 経緯や背景と前提
・申し込みフォームにiframeを使っている為、Google広告のトラッキングデータを入れ込むのは複雑
・サンクスページを作成してGoogleのトラッキングコードを埋め込む方向に
・LP→申し込み記入→サンクスページという流れを作る
・本サイトは静的ページのため（ヘッダー&フッターなど共通化すると便利かもです)

**Comment by tomonishintaku** [comment]
@TAKUOO 
お疲れ様です。本件について着手しようとしているのですが、Gitでクローンしてきた「worldwideauction」フォルダのindex.htmlをローカルで開いてみたところ、以下のような表示になっており、https://worldwide-auction.monobank.jp/　とはかなり表示に差異が出ております。
https://www.dropbox.com/s/083jtiqip0k0lhx/capture_2021-04-01.png?dl=0

見たところ静的ファイルのようですが、ローカル作業時には、何か操作が必要なのでしょうか。
お手数ですが、ご教示のほどよろしくお願いいたします。

**Comment by TAKUOO** [comment]
@tomonishintaku 
index_.html
はどうですか？

**Comment by TAKUOO** [comment]
ちなみにcssの崩れは本番環境ではなく、昨日画面共有したものに当たっているためだと思います。

**Comment by tomonishintaku** [comment]
index_.html が、先程お送りした画面キャプチャの状態になります。
また、これはどういう意味でしょうか。ローカル状態では、本番と同じ表示にはならないということでしょうか。
＞本番環境ではなく、昨日画面共有したものに当たっている

**Comment by TAKUOO** [comment]
index_.htmlではなくindex.htmlを元に改修お願いします!

**Comment by tomonishintaku** [comment]
承知しました。では、ローカルでの表示は気にせず進めたいと思います。
ご回答いただきありがとうございます。
