### ISSUE TITLE
MWA | Google広告バナー作成

### ISSUE THREAD

**Issue by TAKUOO** [TAKUOO/rubydesign_works#27]
#### 目的
BtoBですが、サイトからの新規顧客獲得

#### やること
google広告で表示するバナーの作成

#### 背景
2021年3月末よりMWAサイトをGoogle広告として掲載中です。そのため、google広告のバナーを作成

#### 詳細
BtoBオンラインオークションを開催してる事を伝えるバナーを作成して欲しいです。
バナークリック→mwaサイトの流れを想定。

- 横長と正方形の2パターン作成(横長:最小1200×628 正方形:300×300）
- キービジュアルは下記のイメージを踏襲
- どこからオンラインで参加可能! BtoBオンライン
- 訴求：今なら入会金無料！12月末まで押し（年会費はかかるのですが記載は不要でいいかなと）

## キービジュアル
figma内に素材をおいてます
https://www.figma.com/file/ys9gkZj3tyUcjkMyDdfEDM/MWA-WEB-SITE?node-id=0%3A1
<img width="1175" alt="スクリーンショット 2021-03-27 7 22 05" src="https://user-images.githubusercontent.com/39471524/112699414-18c6fa80-8ecf-11eb-9b50-93b18de3732d.png">

## 訴求
今なら入会金無料！12月末まで押しはこちらのバナーを参考
<img width="689" alt="スクリーンショット 2021-03-27 7 42 05" src="https://user-images.githubusercontent.com/39471524/112699792-f08bcb80-8ecf-11eb-965b-3db721a12859.png">

**Comment by mebius-design** [comment]
本件につきまして、２点質問させて頂きたい事がございます。

まず、バナー自体も下記Figma内に作成した方が良いでしょうか？
https://www.figma.com/file/ys9gkZj3tyUcjkMyDdfEDM/MWA-WEB-SITE?node-id=0%3A1

２点目に、今なら入会金無料！12月末まで押し　というのは
今なら入会金無料！12月末まで有効　＋　参加登録する　の内容で
お間違いないでしょうか？

もし誤りなどがあれば、ご指摘頂けますと幸いです。

**Comment by TAKUOO** [comment]
はい！
バナー内にプラスアルファの特典として盛り込むイメージです。

**Comment by mebius-design** [comment]
すみません、別件対応の関係でご連絡が遅れました。
上記ありがとうございます！
今からバナー作成を進めさせて頂きます。

**Comment by mebius-design** [comment]
本件、確認させて頂きたいのですが
メイン文言は
・どこからオンラインで参加可能! BtoBオンライン
上記で、間違いないでしょうか？

どこからオンライン→どこからでもオンライン
上記のように調整できればと思いますが
BtoBオンライン　の部分が少し気にかかりました。
<img width="855" alt="スクリーンショット 2021-03-29 16 27 18" src="https://user-images.githubusercontent.com/52993138/112801366-c5f66a00-90ab-11eb-809c-4702437c4b8c.png">

**Comment by TAKUOO** [comment]
こちらの文言で問題ないです！こっちの方が良さそうなど有ればよしなに変えてもらってかまいません。

![image](https://user-images.githubusercontent.com/39471524/112802292-f8549700-90ac-11eb-8951-d8a89abc5ad9.jpeg)

**Comment by mebius-design** [comment]
ありがとうございます！承知いたしました。

**Comment by mebius-design** [comment]
先ほどは、お手数をおかけしてしまい申し訳ありませんでした。
アドバイス、大変助かりました！ありがとうございます。

先ほど、編集が完了しましたのでご報告させて頂きます。
もしかしたら、ボタンエリアは　緑　の方が強調できるかもしれないので
B案として、作成させて頂きました。

ご確認の程、よろしくお願いいたします。
https://www.figma.com/file/ys9gkZj3tyUcjkMyDdfEDM/MWA-WEB-SITE?node-id=0%3A1

![スクリーンショット 2021-03-29 18 15 17](https://user-images.githubusercontent.com/52993138/112815174-014c6500-90bb-11eb-85f0-9ae93b55a44f.png)

**Comment by TAKUOO** [comment]
いい感じですね！文言はすみませんが、オンラインではなく、リアルタイムネットオークションに統一お願いします！

**Comment by mebius-design** [comment]
承知しました！修正いたします。

**Comment by mebius-design** [comment]
先ほど、修正完了しましたので
ご確認の程、よろしくお願いいたします。
https://www.figma.com/file/ys9gkZj3tyUcjkMyDdfEDM/MWA-WEB-SITE?node-id=0%3A1

![Uploading スクリーンショット 2021-03-29 18.35.55.png…]()

**Comment by mebius-design** [comment]
先ほど、修正完了しましたので
ご確認の程、よろしくお願いいたします。
https://www.figma.com/file/ys9gkZj3tyUcjkMyDdfEDM/MWA-WEB-SITE?node-id=0%3A1

![スクリーンショット 2021-03-29 18 35 55](https://user-images.githubusercontent.com/52993138/112817764-c3047500-90bd-11eb-87e2-2ecbf9a14347.png)

**Comment by TAKUOO** [comment]
有難うございます！横長のバナーは、少し違和感あるので文字サイズ等また調整お願いするかもですが、助かりました！

**Comment by TAKUOO** [comment]
バナーは少しだけ調整させもらいましたmm
これで一旦問題ないと思うので完了にします！
<img width="1346" alt="スクリーンショット 2021-03-30 8 20 27" src="https://user-images.githubusercontent.com/39471524/112911679-e6b4d300-9130-11eb-8d15-d92f3a0063c1.png">
