### ISSUE TITLE
ものばんく | チャリティーオークションチラシ作成

### ISSUE THREAD

**Issue by TAKUOO** [TAKUOO/rubydesign_works#28]
ものばんくが下関大丸店と協賛して行うチャリティーオークション第1段
これからチャリティーオークションを定期開催しそうな感じです。

## 参考資料
https://www.dropbox.com/sh/88s2dhba2n2ev05/AAA6RUindaNxXb9qj_yF7Zr7a?dl=0

**Comment by TAKUOO** [comment]
@mebius-design 
チャリティーオークションについてのやりとりはこちらです。
ものばんくの北村さんからのコメントを見ると
おそらくスタイリングでお手伝い、または良きアドバイスご提案くださいとのニュアンスかなと。
<img width="827" alt="スクリーンショット 2021-04-02 12 27 42" src="https://user-images.githubusercontent.com/39471524/113377384-1c66ef80-93af-11eb-94c5-86acbb703116.png">

**Comment by mebius-design** [comment]
@TAKUOO 
ご共有ありがとうございます。
なるほどです。ラフを元にアドバイス的な感じなのですね。
参考資料も、追って拝見させて頂きます。

**Comment by TAKUOO** [comment]
@mebius-design 
ズレがあるとまずいので、ラフを元にこちらで正式なデザインを作成。
こうした方がいいというのがあれば提案ほしいという事ですね！
また開始する際、会話できたらお願いします。

**Comment by mebius-design** [comment]
@TAKUOO 
ご連絡が遅れてしまい、失礼いたしました。
ありがとうございます！本件、開始前に
確認も兼ねて、通話できればと思いますので、
こちらこそ、よろしくお願いいたします。

**Comment by TAKUOO** [comment]
@mebius-design 
あまり情報にならないかと思いますが、こちら共有しておきます。
相手側のリクエストです。
![スクリーンショット 2021-04-05 8 39 17](https://user-images.githubusercontent.com/39471524/113524976-2ece6c80-95ed-11eb-86d8-6d388ab83121.png)

**Comment by mebius-design** [comment]
@TAKUOO 
ご共有ありがとうございます！
伝えてほしい要項をピックアップして頂けているのは助かります。

ご状況にもよりますが
4/7（水）10時頃　に、開始前のMTGを行わせて頂けますと幸いです。
引き続き、よろしくお願いいたします。

**Comment by TAKUOO** [comment]
下記裏面の内容となります。

まだ文章など確定していない要素がありますので確定次第すぐに連絡します。
①お問い合わせ先（メール、電話番号、LPQR）
②ジャンル→マストで入れる説明
③寄付できないアイテムの掲載
④お見積もり無料
②と③についての詳細で
商品リスト「イラスト形式＋簡単なコメント」
　ジェエリー・貴金属
　ブランド品（バック・財布・衣類等）
　腕時計
　家電
　着物
　骨董美術
　そのた（レジャー品）
出品できない商品
　動物の剥製
　家具・仏具
　キッズベビー用品 （編集済み）
④の「見積もり無料」はいらないと思われましたら削除してください。 （編

**Comment by TAKUOO** [comment]
<img width="507" alt="____________________________2021-04-07_10 40 39" src="https://user-images.githubusercontent.com/39471524/113801241-64ad5580-9793-11eb-996c-4e68215f7a3e.png">

**Comment by TAKUOO** [comment]
@mebius-design 
![スクリーンショット 2021-04-07 11 34 05](https://user-images.githubusercontent.com/39471524/113802161-2d3fa880-9795-11eb-88ee-5b61b0a5715e.png)

**Comment by TAKUOO** [comment]
@mebius-design 
表面のデザインにて、以下の要望が来ています。今日難しければ明日で大丈夫です！

①付け加える情報
以下の二つの情報をチラシを見たときに、パッとわかりやすいようにデザインしてほしいです。
・発送方法（店頭・郵送）をざっくりと分かりやすいように明記する。
→店頭では商品を持ち込んで頂くだけだが、郵送ではお客様が出品キットを請求する必要があり、全て送料無料で行う。という内容を入れて頂きたいです。
・オークションの透明性を上げる内容を記載する。
→市役所と協力するイベントであることや、プロの鑑定士、バイヤーによるオークションであることなどを記載し、一般の方が安心してオークションに参加できるように促したいです。
②ラフ中部のイラストで出品できない商品のイラストを変更する。
→大型家電や、家具は出品できないのでそのイラストを衣類や、他の出品できるものに変更して頂きたいです。

**Comment by TAKUOO** [comment]
@mebius-design 
以下具体的なアクションです。

> 発送方法（店頭・郵送）をざっくりと分かりやすいように明記する。

 step箇所に追加する。

【お客様側の郵送時の流れ】
出品キットの請求→必要書類の記入→出品商品の発送→査定結果及び寄付に対しての同意→競順の通知→オークション視聴
という流れ

> オークションの透明性を上げる内容を記載する。

表紙の文章部分に追加する。

> ラフ中部のイラストで出品できない商品のイラストを変更する。

修正済み

**Comment by mebius-design** [comment]
@TAKUOO 
ご共有ありがとうございます！
具体的なアクション内容についても、助かります。
全て、表面の修正内容という認識でお間違いないでしょうか？

表面に関しては、明日に対応予定とさせて頂けますと幸いです。

**Comment by TAKUOO** [comment]
です！認識あってます！

**Comment by mebius-design** [comment]
@TAKUOO 
お疲れ様です。
本日の進捗報告をさせて頂きます。

本件、
表面は、イラストの差し替えのみ
裏面は、楽器・雑貨類への差し替え、右下枠内の文言、枠自体の大きさ調整（パターン追加）
上記を行わせて頂きました。

枠の大きさですが、枠間の余白（上下左右の均等さ）も踏まえると、
縮小度合いは、このくらいが良いかと感じております。
※裏面　連絡先については、更新され次第、差し替え予定です

この後、表面の質問項目についても
記載をさせて頂きます。

![ss_0407](https://user-images.githubusercontent.com/52993138/113838223-888b8e00-97c9-11eb-87b1-9fd880170184.png)

**Comment by mebius-design** [comment]
２点目に、表面の修正に関して、
事前に確認させて頂きたい事がございます。

————————————————————————————

＞発送方法（店頭・郵送）をざっくりと分かりやすいように明記する。
対応：step箇所に追加する。

上記ですが、
オークションそのもの流れ　と　郵送時の流れ　を
一括で見せた方がわかりやすいと感じたので
一度、表面に追記させて頂こうと思います。

つきましては、現在の表面のStepの下に
新たに　郵送時の流れ　を追加する認識でよろしいでしょうか？

その際、注意事項や具体的な説明エリア　のスペースは
・残したままの方が良いのか
・そのスペース上に、Stepを追加して良いのか
も、教えて頂けますと幸いです。

————————————————————————————

＞オークションの透明性を上げる内容を記載する。
対応：表紙の文章部分に追加する。

上記ですが、下記のような文章表現ではいかがでしょうか？
※市役所というのが、下関市役所で良いのかも、ご確認いただきたいです

↓↓↓

モノをチャリティオークションに出品し
落札金額の全額をそのまま医療従事者に寄付できる。
それが”ものはぴ”です。

本サービスは下関市役所と協力し、
プロの鑑定士・バイヤーの方によるオークションであるため
一般の方が安心して参加できる内容になっています。

また、このオークションでは運営で頂いた手数料も全額寄付しながら
みなさんと医療従事者を応援できる場をつくっています。

————————————————————————————

以上になります。
明日にご確認頂ければと思いますので
引き続き、よろしくお願いいたします。
※明日は、11時〜18時の間を目安に、稼働させて頂く予定です

**Comment by TAKUOO** [comment]
@mebius-design 
>オークションそのもの流れと郵送時の流れを 一括で見せた方がわかりやすい

ですね！

>注意事項や具体的な説明エリアのスペースは残したままの方が良いのか

残しの可能性が高いので郵送のフローは持ち込みの流れと合流させるかのレイアウト配慮いりそうです。


> 本サービスは下関市役所と協力し、
> プロの鑑定士・バイヤーの方によるオークションであるため
> 一般の方が安心して参加できる内容になっています

いいですね！下関市役所かは連絡とれ次第連絡します。

**Comment by TAKUOO** [comment]
下関市役所で良いです！

**Comment by mebius-design** [comment]
@TAKUOO 
各所、ご回答頂きありがとうございます！

そうしましたら、郵送のフロー追加に関しては
注意事項や具体的な説明エリアのスペースは確保した上で
一度、進めさせて頂ければと思います。

現状での、表面の修正が完了次第
ご報告させて頂き、情報提供のご状況次第で
明日に少し、稼働時間を回すかどうかも、検討させて頂けますと幸いです。

**Comment by TAKUOO** [comment]
@mebius-design 
以下をこちらで変更してます。

データ元: 20210409_チャリティー_edit_amemiya.aiの(裏面)

#### 全体デザイン変更
（仮説1）裏と表でメリハリがある方がいいのでは
（仮説2）デザイン要素が少なくシンプルなので文字のジャンプ率などを見直しても良い出のは

初期段階の構想から、作成後、上記のような仮説が出たため、メリハリのあるデザイン、
タイトル部分などの文字ジャンプ率などの見直しとデザイン調整

#### タイトル部分（文言&デザイン変更）
・オークションに→チャリティオークションに（通常オークションではないのでチャリティを強調がいいかなと）

#### 出品できる&出品できない（デザイン&アイテム変更）
・腕時計部分、アップルウォッチは家電にも入りそうなため、腕時計に変更
・雑貨のゲーム機リモコンは家電だと思うので家電へ。
・ゲーム機移動でスペースが空くので雑貨類にアニメのフィギュアっぽいものを追加
・アイコンが少し小さいので調整

#### 無料査定（文言&アイコン変更）
・訴求文言としては弱く感じたため、プロ鑑定士や無料査定を目立つ形に。
・企画書の一部を抜粋してより詳細な文章に調整。
・無料査定の枠線部分もメリハリがないため、少し厚めに調整
・アイコンは査定を連想できるアイコンに変更

<img width="609" alt="スクリーンショット 2021-04-12 6 36 21" src="https://user-images.githubusercontent.com/39471524/114323853-21bbfb00-9b62-11eb-8627-37168b907006.png">

**Comment by TAKUOO** [comment]
@mebius-design 

#### mtgでの決定事項

(全体共通)
・全体の色目を医療などで使われる青系に変更（ものばんくのロゴが緑なため、目立ちすぎ問題、少し会社は隠したい）
・オークションではなくオンライン形式でのオークションという文言に変更
・文言統一でモノは”もの”に変更

(表面)
・「全体の流れ」ではなく「出品から寄付までの流れ」に変更
・流れは郵送と持ち込みの2つのパターンがあることをわかりやすく
・郵送するユーザーはリテラシーが高いため、郵送の細かな流れは削除。詳細の流れはLP側で。そのため、LPへに流す促す後押し文言も追加
・持ち込みの方は、高齢者の方も多くリテラシーが低いためチラシで説明（流れを少し細かく、下記のもので変更お願いします）
・具体的な説明エリアには手数料の事とCtoBであることの説明（プロのバイヤーによるオークションであること、企画書参照）
・ロゴ位置も下部に変更

・中央の文字の変更
①今回のオークションに対して市役所は告知協力等のレベルのため「下関市役所と協力」という直接的な表現よりも「下関市役所を通じて医療従事者へ寄付する」という関与してることを示唆する内容に変更する。

②「手数料も全額寄付」という表現を「手数料から一部経費を差し引いて全額寄付する」という内容に変更する。

③最後に「あなたの使わなくなったモノがコロナ禍のヒーロー（医療従事者）を支える力になる」という内容の一文を添える。


出品から寄付までの流れ
1.ものばんく(下関店or大丸店)に持ち込む
2.鑑定士が査定<チャリティオークションの落札予想価格(予想寄付額)の決定> 寄付申込書の記入をするを一文入れる。
オンラインオークションである事を記載
3.競り順をメールまたはお電話でご連絡
4.チャリティオークション（オンライン形式であることを記載）
5.医療従事者に全額寄付（下関市役所を通じて、寄付場所と告知のため）
6.ご報告書が到着


ユーザーの属性整理
・持ち込みするユーザー：オークションや買取、インターネットへのリテラシーが低い
・郵送：買取や査定、オークションへのリテラシーが高い

(裏面)
・チャリティオークションの実機での画像を設置
・、出品できるモノについての以下の具体的な内容をイラストの下に記載する。
「家電製品:発売から5年以内の製品ジュエリー・貴金属・腕時計:壊れているモノもOK」
・無料査定だと、買取のイメージが強いので下記のニュアンスに変更
「査定後の出品取り消しは可能で、気軽に査定に来て欲しい」という内容
・お問い合わせ箇所は、株式会社大丸松坂屋百貨店か下関大丸の表記を株式会社ものばんくと並列表記として記載
お問い合わせ先もモノハピ用に変更予定


#### Q&A
・下関市役所の立ち位置ってどこですか？
→医療系で使われる青系で調整
