### ISSUE TITLE
WorldWideAuction | LP申し込みサイト改修

### ISSUE THREAD

**Issue by TAKUOO** [TAKUOO/rubydesign_works#29]
こちらのサイトの改修
https://worldwide-auction.monobank.jp/

#### 改修内容
-   メインイメージが現状の物は古いので、webアプリとネイティブアプリがわかる下記のデザインに変更
-  強みと申し込みフォームの間に流れがわかるコンテンツを入れる(コンテンツは、mwaサイトのものを参考)

#### 背景
このサイトは、取り急ぎで作ったサイトのため、翻訳サイトを追加する際に、遷移元のMWAのサイトに合わせたもにしましょうかという話から。

キービジュアル
<img width="1175" alt="112699414-18c6fa80-8ecf-11eb-9b50-93b18de3732d" src="https://user-images.githubusercontent.com/39471524/112720891-54e87280-8f44-11eb-8764-7de721c924cd.png">

流れのコンテンツ
<img width="1073" alt="スクリーンショット 2021-03-27 8 51 55" src="https://user-images.githubusercontent.com/39471524/112720898-5d40ad80-8f44-11eb-8ce6-d102f22bc197.png">

**Comment by tomonishintaku** [comment]
@TAKUOO
こちら着手したいと思いますが、キービジュアルの元データなどはありますでしょうか。
GooglePlayの箇所のQRコードなど、適宜切り出せればと思います。
お手数ですが、確認のほどよろしくお願い致します。

**Comment by TAKUOO** [comment]
@tomonishintaku 
figma招待してます！
ちなみにindex.htmlにはキービジュアルをすでにコーディング中のため、
先日お伝えしたようにキービジュアル以外の箇所をお願いします。
コーディングはスマホでも見れるようにページ全体調整ください。
https://www.figma.com/file/ys9gkZj3tyUcjkMyDdfEDM/MWA-WEB-SITE?node-id=0%3A1

**Comment by tomonishintaku** [comment]
@TAKUOO 
早速のご回答ありがとうございます。
Figmaのデータについて確認できました。
承知しました。では、キービジュアル以外の申し込みの流れの部分について進めたいと思います。

**Comment by TAKUOO** [comment]
@tomonishintaku 
有難うございます！
申し込みの流れ部分含め、強みの箇所など調整必要そうだと思う部分は
適宜調整ください。
土日という事で、連絡が遅くなる場合もありますがご了承くださいmm
