### ISSUE TITLE
MEKIKI | サービス概要のチラシデザイン修正

### ISSUE THREAD

**Issue by TAKUOO** [TAKUOO/rubydesign_works#30]
#### やる事
MEKIKIサービス概要のチラシデザインの修正まで

#### 締め切り
4/5,6,7あたりで目安で進行ですが、少しずらせそうです。あくまでも目安。

#### 背景
MEIKIKIとは
株式会社メキキは、ものの鑑定力を強みとする株式会社ものばんくと課題解決のAIソリューション を強みとする株式会社チームAIBODの合弁会社。鑑定士の目利き力を人工知能化しモノの価値の適切な査定を実現、 眠っている動産の流通を活性化

以下サイトを参考ください
https://www.mekiki.ai/

#### 修正内容
(初回)
1ページ目右側（表紙部分）
①「2020年2月末までにご契約のお客様に3大特典付！」→「2021年12月末までにご契約のお客さまに特典付！」
②「パシャっと撮るだけで買取相場が分かる！」→削除。「パシャっと」のアイコンも削除
③特典1の「入会金65％OFF」の下に「55,000円→19,250円」
➃特典2→ものばんくワールドワイドオークション2021年度入会金、会費無料！
  上記の下に「入会金22,000円→無料」「会費月額1,100円→無料」
⑤特典3→ものばんくワールドワイドオークションご入会でMEKIKI月額利用料半額！
 上記の下に「月額11,000円→5,500円」

#### データ
イラレのaiはデータはこちら
https://www.dropbox.com/sh/qlk7vgbpsii00kt/AAAG-V9OIdeh8PbNeSQcAAxTa?dl=0

**Comment by TAKUOO** [comment]
追加修正分
```
【1ページ目左側（表紙部分）】
⑥「MEKIKI」の上の文言を以下に修正
　→「鑑定・査定業務のサポートツール」
【1ページ目左側（最終ページ）】
①「買取り損失が圧倒的に減ります」から「サービスアップデート」の項目部分まで全て削除してください。
　（この部分は白紙状態になって大丈夫です）
②松井さんがアドバイスくださったように、「無料会員登録」のQRコードに加えて、申込書をダウンロードできるように
　してください。（申込書添付します）
　「FAXでもお申し込みいただけます」みたいな文言を入れてもらって、FAX番号も掲載いただければと。
　FAX番号：050-3606-3324
③一番下の「お申し込みはこちらへアクセス」の部分、URLも含めて削除してください。
【2ページ目左側】
①「約70万件の取引データを熟知した・・」の文言を「約70万件の取引データから最新相場を検索」に修正してください。
②「鑑定・査定サポートMEKIKIは・・」から始まる文言を下記に修正してください。
　　→MEKIKIは鑑定・査定のサポートツールで商品の特定から相場検索まで行うことが出来るサービスです。
　　　キーワード検索はもちろん、査定中の商品をスマホやタブレットで撮影して画像検索が可能です。
　　　検索結果からヤフオク、楽天などの売価を調べることもできます。
　　　相場価格は、業者間オークション過去10年分、約70万アイテムのデータの中から検索可能。常に最新版をご提供します。
　　　ブランドバッグ7点で[商品特定]から[買取価格算出]まで最短10分！
　　　MEKIKIを使って鑑定・査定時間を短縮することで、バイヤーだからこそ出来る接客サービスが実現可能です。　　
③「ブランドバック7点の査定ケースで比較」→「ブランドバック」を「ブランドバッグ」に修正
　　同じ個所の「メキキ：商品画像でモノの特定から・・」の部分を「商品検索でモノの特定から相場価格算出まで3ステップ10分で完結！」に修正
　　↑の下の3ステップの1ステップ目「画像撮影」を「キーワード入力」「商品撮影」に修正（2段になって大丈夫です）
【2ページ目右側】
①「常に相場感覚を最新にキープする！」の下に「買い取り損失が圧倒的に減ります」の文言を追加
②ミニスピーディの写真を添付の写真に差し替え
③↑「CHANEL」ココマーク ピアス
　程度Aランク
➃「ミニスピーディー落札相場推移」→「ココマークピアス落札相場推移」に修正
⑤折れ線グラフのデータを下記に変更
　→Aランク落札相場　　　　　Bランク落札相場
　　2019.6　22,000円　　　　  17,000円　　
　　2020.1　27,000円　　　　  15,500円
　　2021.2　78,000円　　　　  58,000円

```

**Comment by TAKUOO** [comment]
追加修正分
現在、表紙部分のイメージはスマホを持っているイメージなんですが、実際は、PC/SPでも見れると認識させたい以降があるので、メインイメージを下記添付しているイメージに変更お願いします。
dropbox内の、`device.png`に変更してください。
必要な素材があれば共有しますのでご連絡ください。

**Comment by mebius-design** [comment]
本件、下記について質問させて頂きたいのですが

＞②松井さんがアドバイスくださったように、「無料会員登録」のQRコードに加えて、申込書をダウンロードできるようにしてください。（申込書添付します）

上記は、QRコードを読み取って申込書をダウンロードする　という解釈で良いでしょうか？
その場合、QRコード画像を頂ければと思います。

**Comment by TAKUOO** [comment]
qrコードは作成次第お渡ししますので、ひとまずアタリでqrコードを置いてもらう感じでお願いします！

**Comment by mebius-design** [comment]
先ほどはありがとうございます！
もう一点、確認とご相談なのですが

＞⑤折れ線グラフのデータを下記に変更
　→Aランク落札相場　　　　　Bランク落札相場
　　2019.6　22,000円　　　　  17,000円　　
　　2020.1　27,000円　　　　  15,500円
　　2021.2　78,000円　　　　  58,000円

上記の修正につきまして、グラフの修正を行いたいのですが
元データなどはありますでしょうか？
イラレのデータだと、画像になっているようです。
![スクリーンショット 2021-03-29 11 10 13](https://user-images.githubusercontent.com/52993138/112778532-b7925900-907f-11eb-9e03-06ace06dbc1c.png)

**Comment by TAKUOO** [comment]
これおそらくwebサービス利用して作成されているんですよね。
作成されたか末藤さんなんで少しお待ち下さいmm
ちなみにデザイン同じ出なくてもいいです。
Googleのエクセルとかでもできそう。

**Comment by mebius-design** [comment]
ありがとうございます！なるほどです。
そうしましたら、自分の方で作成の上で
差し替えを行わせて頂ければと思います。
※photoshopなど、自分が早く作成できるツールで作成させて頂く予定です

**Comment by TAKUOO** [comment]
有難うございます！助かります。
canvaというサービスも手軽に行けそうです。
共有まで。判断は雨宮さんにお任せします！
https://www.canva.com/design/play?template=MADZDHV8-Yw&category=tADWs7A4Dr8

**Comment by TAKUOO** [comment]
@mebius-design 
dropbox内に表紙を調整したもの01_edit_matsui.aiいれてます。
雨宮さんのデータに移植するなどして修正と調整お願いします。
ちなみに画像は手持ちのフォントがないため、テキスト箇所にマーカー引かれてる状態です。
ただFTC加盟店様〜などの部分のあしらいや、デバイス下のマッピングぽいデザイン部分は線が四角の枠からはみ出したり適当に配置してるので、調整お願いしたいです！
<img width="494" alt="スクリーンショット 2021-03-30 7 25 44" src="https://user-images.githubusercontent.com/39471524/112908841-3f816d00-912b-11eb-8140-4cdadeda0032.png">

**Comment by TAKUOO** [comment]
@mebius-design 
こちらは、昨日mekikiさんへpdfでの確認連絡してます。
また何かあればよろしくお願いしたいと思います。
