### ISSUE TITLE
MEKIKI | ABOUT箇所修正

### ISSUE THREAD

**Issue by TAKUOO** [TAKUOO/rubydesign_works#31]
MEKIKIサイトのメンバーの修正
https://www.mekiki.ai/

メンバーが抜けため削除をお願いします。
メンバーを削除したさいPC/SPで崩れがないかの確認も合わせてお願いします。

#### 削除するメンバー
粟屋さん、中塚さん、ホセさん

![スクリーンショット 2021-04-06 13 17 44](https://user-images.githubusercontent.com/39471524/113658346-d83f5c00-96da-11eb-982c-ef3301ea696d.png)

**Comment by TAKUOO** [comment]
@tomonishintaku 
local_mekikiをGithubにあげてますので、プルすればファイル出現するかと思います。
できれば作業完了後、スクショも頂けると助かります。確認しやすいので。
サーバーアップはこちらで行います。

**Comment by tomonishintaku** [comment]
@TAKUOO 
お疲れ様です。
Pullを行い、Mekikiフォルダについては問題なく出現しました。
しかし、その時点で、以下のような変更点がすでにstageに上がっているようです。

        deleted:    css/style.css
        deleted:    css/style.css.map
        deleted:    css/style_sp.css
        deleted:    img/_awaya_on.jpg
        deleted:    img/about_img_mono@2x.jpg
        deleted:    img/ai_img.jpg
        deleted:    img/aibod.svg
        deleted:    img/alex_off.jpg
        deleted:    img/alex_on.jpg
        deleted:    img/awaya_off.jpg
        deleted:    img/awaya_on.jpg
        deleted:    img/bg_products@2x.jpg
        deleted:    img/device.png
        deleted:    img/device.svg
        deleted:    img/entrySheet.pdf
        deleted:    img/eva.png
        deleted:    img/eva_posi.png
        deleted:    img/facebook-logo-button.svg
        deleted:    img/fakecheckerLogo_posi.svg
        deleted:    img/firstImg.png
        deleted:    img/footer_bg@2x.jpg
        deleted:    img/fv-mekiki.mp4
        deleted:    img/general_business_owner_action_plan.pdf
        deleted:    img/graph.svg
        deleted:    img/graph_en.svg
        deleted:    img/ios_app.svg
        deleted:    img/ipad.png
        deleted:    img/iwashita_off.jpg
        deleted:    img/iwashita_on.jpg
        deleted:    img/joe_off.jpg
        deleted:    img/joe_on.jpg
        deleted:    img/jose_off.jpg
        deleted:    img/jose_on.jpg
        deleted:    img/logo.svg
        deleted:    img/logo_nega.svg
        deleted:    img/main_bg.jpg
        deleted:    img/matsuo_off.jpg
        deleted:    img/matsuo_on.jpg
        deleted:    img/mekiki_logo.svg
        deleted:    img/monobank.svg
        deleted:    img/monograph.svg
        deleted:    img/monopedia.svg
        deleted:    img/moriyama_oN.jpg
        deleted:    img/moriyama_off.jpg
        deleted:    img/murakami_off.jpg
        deleted:    img/murakami_on.jpg
        deleted:    img/nakatsuka_off.jpg
        deleted:    img/nakatsuka_on.jpg
        deleted:    img/ogp.jpg
        deleted:    img/okuno_off.jpg
        deleted:    img/okuno_off_.jpg
        deleted:    img/okuno_on.jpg
        deleted:    img/okuno_on_.jpg
        deleted:    img/otsuru_off.jpg
        deleted:    img/otsuru_on.jpg
        deleted:    img/product_logo.svg
        deleted:    img/search.svg
        deleted:    img/slide01.png
        deleted:    img/slide02.png
        deleted:    img/slide03.png
        deleted:    img/slide04.png
        deleted:    img/suefuji_off.jpg
        deleted:    img/suefuji_on.jpg
        deleted:    img/tech-mekiki.mp4
        deleted:    img/twitter-logo-button.svg
        deleted:    img/wave.svg
        deleted:    img/who_img.jpg
        deleted:    img/yoshida_off.jpg
        deleted:    img/yoshida_on.jpg
        modified:   index.html
        deleted:    js/common.js
        deleted:    js/main.js
        deleted:    js/smart-crossfade.js
        deleted:    terms/privacy/index.html
        deleted:    terms/rule/index.html

現時点で私が触っているのは「modified:   index.html」なのですが、それ以外のステージングに上がっている変更点はどのように扱えばよいでしょうか。

お手数ですが、確認のほどよろしくお願い致します。

**Comment by TAKUOO** [comment]
@tomonishintaku 
変更したもののみステージにあげてあとは、破棄して問題ないと思います。
