### ISSUE TITLE
ものばんく｜チャリティーオークションサイト

### ISSUE THREAD

**Issue by TAKUOO** [TAKUOO/rubydesign_works#33]
ものばんくと企業とのコラボ企画。チャリティーオークションのLP作成。
LPのターゲットははCで、ものを売りたい方。
企画の事業モデルはBtoCになります。
LPはチラシを元に、ものばんくのインターンの大学生が作成。
今回はそのアドバイスやレビューとなりそうです。

**Comment by TAKUOO** [comment]
スレッドと同じものをこちらにも追加しておきます。

ものばんくのインターンの大学生がチャリティオークションLPのワイヤーを作ってるんですが、
構成などでなにかおかしいところ、こうした方がいいよってところのアドバイスしてもらえないでしょうか？
SLACKのスレッドなどにコメント書いてもらえれば、そのままお伝えします。

https://xd.adobe.com/view/4c288d81-6710-4d9b-88f9-9e4c5f92bea3-197b/

**Comment by mebius-design** [comment]
@TAKUOO 
XDにコメントさせて頂きましたので
お手すきの際に、ご確認頂けますと幸いです。

**Comment by TAKUOO** [comment]
@mebius-design 
すみません。こちらはスラックでコメントお願いできないでしょうか？
対クライアントのため。。

**Comment by TAKUOO** [comment]
@mebius-design 
なのでxdのものは削除くださいmm

**Comment by mebius-design** [comment]
@TAKUOO 
大変失礼いたしました。削除の上で、スラックの記載いたします。
