### ISSUE TITLE
WorldWideAuction | LP申し込みサイト キービジュアル調整

### ISSUE THREAD

**Issue by TAKUOO** [TAKUOO/rubydesign_works#35]
1.キービジュアルのレスポンシブ時のデザイン調整
2. キービジュアルに「オークション既存会員はこちら」のボタン追加

<img width="1175" alt="112720891-54e87280-8f44-11eb-8764-7de721c924cd" src="https://user-images.githubusercontent.com/39471524/114255581-94589980-99ef-11eb-8241-101cb0f58460.png">

**Comment by tomonishintaku** [comment]
@TAKUOO 
こちらは、現在のメイン画像をバックグラウンドイメージとして扱うと同時に、その画像を一枚に合成して使用など、構成自体を変えても問題ないのでしょうか。
もし構成はママということであれば、追加ボタン群はpositionなどで調整して設置しようかと思います。

確認のほどよろしくお願い致します。

**Comment by TAKUOO** [comment]
@tomonishintaku 
構わないです。ただ、イメージのようなバランスでお願いします！
ご理解されているかと思いますが、SP時はQR不要です。念の為に共有。
