### ISSUE TITLE
MEKKIKI | カードUIデザインのリデザインとパターン作成

### ISSUE THREAD

**Issue by TAKUOO** [TAKUOO/rubydesign_works#38]
## 課題
走りながら機能追加をしてきたため
カード内でUI破綻が起こっている

## 問題
・UI内での表示するアラートやタグの表示被りがあり適切な表示ができない
・TOPページでお気に入りボタンが押せない
・詳細なランクを表示したいが情報が多くどこに配置したらいいのか、わからない

## 目的

破綻しないカードデザイン
分かりやすく、使いやすいカードデザイン

## ゴール
課題・問題の改善ができていること

## やること
火曜にカードデザインを担当者と検討したいため、以下のアクションを行う

情報共有(0.5h)
デザインリサーチ(2h)
カードUIのリデザイン(2h)
デザインシステム作成(1h)

### 現状のアラート表示
ステータス： 終了/SOLD/売り切りまであと少し/売り切り
タグ: ライブアイテム/ライブ配信中
落札権利あり
お気に入り

### 今回新たに表示させたいもの
外観ランク,内観ランク
簡単に言えば、外の品質と内部の品質

**Comment by TAKUOO** [comment]
### 現在はこのような形でずらっと一覧で並んでいます。
<img width="1166" alt="スクリーンショット 2021-04-16 6 36 21" src="https://user-images.githubusercontent.com/39471524/114941492-33611380-9e7e-11eb-949b-1b1f2d7de460.png">

### お気に入りが押しにくい事象
<img width="1166" alt="スクリーンショット 2021-04-16 6 36 21" src="https://user-images.githubusercontent.com/39471524/114941722-7a4f0900-9e7e-11eb-8993-6eeac8c9ec6c.png">

**Comment by TAKUOO** [comment]
@mebius-design 
あとリサーチしたものは、どのサイトをみたのかなどissue内にリストで書いてもらえると助かりますmm

**Comment by mebius-design** [comment]
@TAKUOO 
すみません、リサーチサイトは
追って、共有させて頂きますmm

**Comment by TAKUOO** [comment]
@mebius-design 
リサーチしたサイト共有よろしくお願いします。

**Comment by mebius-design** [comment]
@TAKUOO 
ご連絡が遅れてしまい、失礼いたしました。
参考に閲覧したのは、下記のサイトです。

具体的なパーツを参考にしたというよりか
全体的なレイアウトと、目立たせる情報のバランス感を参考した形になります。
ご確認の程、よろしくお願いいたします。

https://auctions.yahoo.co.jp/list5/23140-category.html
https://search.rakuten.co.jp/search/mall/オークション/
https://www.amazon.co.jp/s?k=PC&__mk_ja_JP=カタカナ&ref=nb_sb_noss
https://zozo.jp

**Comment by TAKUOO** [comment]
@mebius-design 
有難うございます！
