### ISSUE TITLE
買取店舗 | お役立ち情報にカテゴリー追加

### ISSUE THREAD

**Issue by TAKUOO** [TAKUOO/rubydesign_works#39]
お役立ちページのカテゴリー区分変更

なんのためにやるのか
SEOとしてものカテゴリからの遷移を増やす為

## 参照ページ
https://monobank.jp/useful

## カテゴリ変更
現状カテゴリ
お役立ち
L 初めての方へ 買取の基礎知識
L 売却・買取時の良くある質問

下記2点については削除予定
- 初めての方へ 買取の基礎知識
- 売却・買取時の良くある質問

変更後カテゴリ
お役立ち
#### 親カテゴリ
L宝石
L時計
Lブランドバッグ
L貴金属
L腕時計
L家電製品
L着物・帯
L骨董品
L美術品
Lその他
Lお酒
L切手・ハガキ

#### 小カテゴリ
L 初めての方へ 買取の基礎知識
L 売却・買取時の良くある質問

**Comment by TAKUOO** [comment]
参照urlのカテゴリは直に書いてるため、こちらもカテゴリ量に応じて変更していただきたいです。

**Comment by tomonishintaku** [comment]
@TAKUOO 
こちらの依頼は、以下WP管理画面から触るという方法になりますでしょうか。
https://monobank.jp/wp-admin/edit-tags.php?taxonomy=category

そうであれば、ご指示いただいた以下内容と、

お役立ち
L 初めての方へ 買取の基礎知識
L 売却・買取時の良くある質問

以下のWP管理画面の内容に相違があるようです。

お役立ち
L 売却のコツ・予備知識
L 知って得する！モノの知識

お手数ですが、ご教示のほどよろしくお願いいたします。

**Comment by TAKUOO** [comment]
@tomonishintaku 
その管理画面からで大丈夫です。

下記が正解ですね。失礼しました。
↓
お役立ち
L 売却のコツ・予備知識
L 知って得する！モノの知識

**Comment by tomonishintaku** [comment]
@TAKUOO 
承知しました。
試みに「宝石」を追加してみましたが、スラッグの命名方法に問題ないかご確認ください。

https://monobank.jp/wp-admin/edit-tags.php?taxonomy=category

また、「親カテゴリ」「小カテゴリ」という箇所のタイトルは新規で何か設定する必要がありますでしょうか。
それとも「お役立ち」を「親カテゴリ」として、すべてぶら下がる形でしょうか。

**Comment by TAKUOO** [comment]
@tomonishintaku 
どうしましょうか。。どうしたらいいと思います？
親カテゴリを親として複数チェックできるので、
「宝石」&「売却のコツ・予備知識」
「宝石」&「知って得する！モノの知識」
ということはできると思うので、
この形を網羅できればどちらでも問題ないかと思います。

新宅さんのご判断にお任せします。
お役立ち ->「宝石」->「売却のコツ・予備知識」
お役立ち ->「宝石」->「知って得する！モノの知識」

**Comment by TAKUOO** [comment]
@tomonishintaku 
すみません。カテゴリ以下に変更になったので、こちらでお願い致しますm(_ _)m
- 宝石
- ブランドジュエリー
- 貴金属
- 時計
- バッグ
- 家電製品
- 着物・帯
- 骨董・美術
- 楽器
- お酒
- 金券・切手

**Comment by tomonishintaku** [comment]
@TAKUOO 

追加カテゴリの変更について承知いたしました。

今回追加するカテゴリについて、「お役立ち」を親カテゴリにしますと、すこし違和感があるので、それとは別に「買取ジャンル」などという新規カテゴリを設けてはどうでしょうか。

買取ジャンル
L宝石
Lブランドジュエリー
L貴金属
L時計
Lバッグ
L家電製品
L着物・帯
L骨董・美術
L楽器
Lお酒
L金券・切手

お役立ち
L 売却のコツ・予備知識
L 知って得する！モノの知識

**Comment by TAKUOO** [comment]
@tomonishintaku 
そうですね。そのほうがいいかもですね。また検討して明日提案してみます。

**Comment by TAKUOO** [comment]
@tomonishintaku 
今ご提案中ですので、しばしお待ちくださいmm
おそらく基本あまり断られる事がないので、大丈夫とは思います。

**Comment by TAKUOO** [comment]
@tomonishintaku 
ご提案通りですのでお願いします。
また、ご提案の内容がよかったみたいで、こんなのやりたいが誘発しちゃったみたいで
今後のアクションが出てます。
こちらは別のissueとして作成しますので、このissueでは大丈夫です。

**Comment by tomonishintaku** [comment]
@TAKUOO 
先方に喜んでいただけたようで何よりです！
そのようにカテゴリー追加を行いましたので、確認のほどよろしくお願い致します。
https://monobank.jp/wp-admin/edit-tags.php?taxonomy=category

**Comment by TAKUOO** [comment]
@tomonishintaku 
スラッグ名もバッチリです！有難うございます。先方に共有しておきます。
ちなみに次回からで大丈夫ですが、進行中はカンバンの「進行中」に、完了すれば確認へ移動をお願いしますm(_ _)m
<img width="1295" alt="スクリーンショット 2021-04-23 7 31 03" src="https://user-images.githubusercontent.com/39471524/115792805-dfb67300-a405-11eb-8fb0-d0615ad5a87b.png">

**Comment by tomonishintaku** [comment]
@TAKUOO 
確認いただきありがとうございます！
また、なしくずしに着手してしまったため、カンバンの設定を失念しており、失礼いたしました。
以降、気をつけます。引き続きよろしくお願いいたします。
