### ISSUE TITLE
買取店舗 | TOPページ&終活・財産見積もりページに提携先コンテンツを追加

### ISSUE THREAD

**Issue by TAKUOO** [TAKUOO/rubydesign_works#40]
## 背景
現在ものばんくでは関連性の高い業種と提携して、相互間の窓口を増やす動きをしています。
第1段としてデイケアサービス提携先としてサイト内で紹介できればと考えてます。

ロードマップ(2週目まで/今週を1周目とした場合)
来週までのアクション
(1周目)貴船ザテラスの提携先エリアの追加(TOPと終活・財産見積もりページ)見せ方デザイン提案
(2周目)実装・公開予定

お願いしたいものは以下のデザイン(SP/PC)と文章を考えて頂きたいです。

### monobankの買取店舗のTOPページと終活・財産見積もりページに提携先コンテンツを追加作成する。
見せ方はお店を探す箇所のカード式のような形で、貴船ザテラスの紹介文と画像、サイトのリンク先のイメージです。
終活ページにも同じものを設置する。

貴船ザテラスのサイトから画像は自由に掲載可能です。
もし使えそうなものがない場合、ものばんく側に連絡して手配してもらおうと思います。
なので、仮でもいいのでデザインを入れておいてください。

http://hp.kaipoke.biz/93g/index.html

![スクリーンショット 2021-04-20 17 28 48](https://user-images.githubusercontent.com/39471524/115367122-df00bf80-a200-11eb-9699-afe5a6dd49fd.png)

**Comment by TAKUOO** [comment]
@mebius-design 
PDF資料も添付しておきます。
[貴船ザテラス.pdf](https://github.com/TAKUOO/rubydesign_works/files/6342123/default.pdf)

**Comment by TAKUOO** [comment]
@mebius-design 
こちらのfigmaファイルにデータいてれます。
https://www.figma.com/file/9xvjwqRRyQcsgGAZALvcxP/whole?node-id=0%3A1

**Comment by mebius-design** [comment]
@TAKUOO 
迅速なご対応、ありがとうございます！
承知いたしました。

**Comment by mebius-design** [comment]
@TAKUOO 
本件、修正させて頂きましたので
ご確認の程、よろしくお願いいたします。
https://www.figma.com/file/9xvjwqRRyQcsgGAZALvcxP/whole?node-id=0%3A1

**Comment by TAKUOO** [comment]
@mebius-design 
有難うございます。先ほどMTG完了したのですがコーディング時の修正でいけそうです。
