### ISSUE TITLE
買取店舗 | 提携先コンテンツのコーディング

### ISSUE THREAD

**Issue by TAKUOO** [TAKUOO/rubydesign_works#41]
下記のissueのデザイン提案のものをコーディングお願いします。
詳細は下記のissueをご確認ください。
 #40 買取店舗 | TOPページ&終活・財産見積もりページに提携先コンテンツを追加

**Comment by mebius-design** [comment]
@tomonishintaku  cc @TAKUOO 
お疲れ様です。本件のデザイン内容につきまして共有させて頂きます。
デザインのfigmaはこちらになります。
https://www.figma.com/file/9xvjwqRRyQcsgGAZALvcxP/whole?node-id=0%3A1
※デザイン内容は添付画像部分

基本的には、monobankの右記ページ（ https://monobank.jp/shop ）と同様の構成になりますが
TOPページは、同ページ内のカラムと合わせる形で
・グレー背景に白枠　その中にコンテンツ（ボタンも含め）
・スマホ時は画像前に、貴船ザテラスの見出し
など、若干異なる部分がございますので
上記を元に、実装を進めて頂けますと幸いです。

ご確認の程、よろしくお願いいたします。

**Comment by tomonishintaku** [comment]
@mebius-design 
お疲れ様です。
以下についてですが、添付画像はどちらで閲覧できますでしょうか。
※デザイン内容は添付画像部分

お手数ですが、確認のほどよろしくお願い致します。

**Comment by mebius-design** [comment]
@tomonishintaku 
上記、画像添付ができておらず
大変失礼いたしました。

画像はこちらになります。
edit_amemiya  と書かれたアートボードが
該当ボードになりますので
ご確認の程、よろしくお願いいたします。

![ss_0426](https://user-images.githubusercontent.com/52993138/116184047-f4726e00-a759-11eb-9730-b3c19a56dc0b.png)

**Comment by tomonishintaku** [comment]
@mebius-design 
早々のご対応ありがとうございます。
助かりました。

**Comment by TAKUOO** [comment]
@tomonishintaku 
変更内容
２社掲載に変更（貴船ザテラスとぼくらの貴船ザサロン）
現状のものは貴船ザサロンの内容となりますので以下に変更。
レイアウトは、お店を探すを探すを参考にしてください。

営業時間と定休日は削除。

## 名前 
貴船ザテラス　
## カテゴリー 
デイサービス
##文章　
貴船小正門前に位置し、10名以下の小規模の地域密着型のデイサービスです。
整骨院や医療機関、理学療法士とも連携し、安全ケアサービスの提供を行っています。

住所　北九州市小倉北区白銀2丁目1-19(貴船小学校正門前)
電話番号　093-777-3326

リンク先　https://bokura-ltd.com/


## 名前 
貴船ザサロン　
## カテゴリー 
短時間デイサービス
##文章
九州モノレール片野駅から、徒歩10分以内。
貴船小学校（正門）前にある、カフェテリアのような雰囲気で、通うのが楽しくなる短時間デイサービスの施設です。

住所　北九州市小倉北区白銀2丁目1-19(貴船小学校正門前)
電話番号　093-980-7341

リンク先　http://hp.kaipoke.biz/93g/139572/index_0004.html

**Comment by TAKUOO** [comment]
貴船ザサロン画像
![zasaron](https://user-images.githubusercontent.com/39471524/116228751-aaf14580-a790-11eb-9a9a-dd122f7cd1ee.jpg)

**Comment by TAKUOO** [comment]
@tomonishintaku 
### タイトル変更
主な提携先→終活に関する専門家・企業ご紹介

### 
リード文変更
ものばんく以外でも・・・
↓
ものばんくでは専門性の高い分野の事業様と連携体制をとっております。ご紹介可能ですのでご相談ください。

<img width="586" alt="スクリーンショット 2021-04-28 7 11 58" src="https://user-images.githubusercontent.com/39471524/116319832-29320400-a7f2-11eb-8088-44aaa9951b99.png">
