### ISSUE TITLE
MEKIKI | ライブオークションカードのUIデザイン

### ISSUE THREAD

**Issue by TAKUOO** [TAKUOO/rubydesign_works#42]

**Comment by mebius-design** [comment]
@TAKUOO 
本タスクに関して、内容の確認をさせて頂きたいのですが
昨日、MTGにてお話頂いた下記の内容＋添付画像の箇所で合っていますでしょうか？

添付画像のカードは、松井さんが調整して頂いたデザインですと
フッターに集約されている認識ですが

もし内容に間違いがあるようでしたら
恐れ入りますが、ご連絡頂けますと幸いです。
※16時前に、着手予定です

●落札カードデザイン
【目的】
LIVE配信中なのか　そうでないのか　の見分けをつきやすくする

・暫定修正事項
ステータス（LIVE配信中など）タグ色のパターン考案
アイテム詳細　というリンク文言の再検討
サムネイル下に、配信中　という表記を追加

![スクリーンショット 2021-04-22 15 05 00](https://user-images.githubusercontent.com/52993138/115664753-33c94500-a37d-11eb-8e2b-6033f2db31c3.png)

**Comment by TAKUOO** [comment]
@mebius-design 

> LIVE配信中なのか　そうでないのか　の見分けをつきやすくする

ここは 現在のステータスがわかるようにするが目的となります。

>暫定修正事項
>ステータス（LIVE配信中など）タグ色のパターン考案

ライブオークション画面のステータスバーにある
開始前/競り中/終了のカラーを元に作成頂ければと思います。

> アイテム詳細　というリンク文言の再検討

こちらよろしくお願いします。

> サムネイル下に、配信中　という表記を追加

こちらは大丈夫です。 
「LIVE中」というのがそれで、昨日担当者とのすり合わせの際に追加しております。

**Comment by mebius-design** [comment]
@TAKUOO 
ご連絡頂き、ありがとうございます！
承知いたしました。
頂いた内容を元に、進めてまいります。

**Comment by mebius-design** [comment]
@TAKUOO 
お待たせいたしました。
本件、完成しましたのでご報告させて頂きます。
https://www.figma.com/file/31Vn3nMe45FipnqK5fKUfO/MEKIKI-UI-BOARD?node-id=1%3A146214

・ステータスのカラー
ライブオークション画面のステータスバーを元に展開させて頂きました。

・アイテム詳細のリンク
こちら、考えていたのですが
・メニュー名もしくはサムネイルをクリックしたら、ページ遷移の挙動を撤廃
・代わりに、金額下部に両方のテキストリンクを配置（LIVEページのリンクは、競り中のみの表示を想定）
上記の調整ですと、わかりやすいように感じたのですが、いかがでしょうか？

・その他変更点
入札する　ボタンは、競り中以外では表示を切り替えても、
わかりやすいと感じ、調整させて頂きました。
※競り中以外では、押せない想定です

・下段カードのご提案
本案は提案ベースになりますが
LIVE中・競り中　は、赤色で統一させても認識しやすいように感じました。
その際、終了はグレーベースで良いかと感じております。

以上になります。

もし、修正が必要な部分があれば
明日のお昼前後で、２時間ほど対応できそうですので
その際に、修正できればと思います。

ご確認の程、よろしくお願いいたします。

**Comment by TAKUOO** [comment]
有難うございます。指示内容はfigmaにコメントを入れております。
補足を下記にまとめてますのでご覧ください。

## 前提
実は、LIVE中になった段階のアイテムがポップアップで表示されます。
少しややこしいのですが、LIVE配信が開始されてる中で「開始前/競り中/終了」があります。
イメージとしては、LIVE中に管理者側が入札開始のボタンを押したり、終了のボタンを押したりする感じです。

> アイテム詳細のリンク

上記前提を元にコメント入れてます。

> その他変更点

提案有難うございます。いいですね。仕様確認必要ですが、提案してみます。

> 下段カードのご提案

上記ベースだと、LIVE中と競り中の色目は同じでなくても良さそうです。
ここはあまり課題がないので現状の色目でお願いします。

**Comment by mebius-design** [comment]
@TAKUOO 
おはようございます。各所、ご確認頂きありがとうございます！

＞実は、LIVE中になった段階のアイテムがポップアップで表示
上記、そういう仕様だったのですね。
解釈に相違があり、失礼いたしました。

13時半から、別件で外出予定の為
それまでに各所の修正を進めさせて頂く予定ですので
よろしくお願いいたします。
※monobank側の修正も確認いたします

**Comment by mebius-design** [comment]
@TAKUOO 
本件、修正させて頂きましたので
ご確認の程、よろしくお願いいたします。
https://www.figma.com/file/31Vn3nMe45FipnqK5fKUfO/MEKIKI-UI-BOARD?node-id=1%3A146214

**Comment by TAKUOO** [comment]
@mebius-design 
確認しました！問題ないです。有難うございます。
初めはサービスの理解だったりするので、サービス理解度あげてもらえてるだけでも助かってます！

**Comment by mebius-design** [comment]
@TAKUOO
ご確認頂き、ありがとうございます！
恐らく、こういったやり取りでサービスの理解度を上げさせて頂くケースも
出てしまうかもしれませんが、引き続き、よろしくお願いいたします。

**Comment by TAKUOO** [comment]
@mebius-design 
いえいえ、理解と観察。サービスデザインの中で一番大切な部分です。
こちらも共有できればと思います。よろしくお願いします。
