### ISSUE TITLE
MEKIKI | ライブオークション画面のUIデザイン

### ISSUE THREAD

**Issue by TAKUOO** [TAKUOO/rubydesign_works#43]

**Comment by mebius-design** [comment]
@TAKUOO 
 先ほどはありがとうございます。
ご相談内容、下記に記載させて頂きます。

Memo

—————————————————————————————————————

●LIVEアイテムページ
●LIVE配信中のページ

【目的】
LIVE配信中なのか　そうでないのか　の見分けをつきやすくする

○最高落札者のエリアのデザイン（本ページの追加事項）
問題点
競り合った時に、ついたり、消えたりする

——————————————————

松井さんの案
左のサイドバー自体をなくす（サイドバー下部の落札カードも含めて）
そこで無くなった要素は、下部のバーに挿入
（例えば、LIVE配信中は下部のバーの色を変更する）

—————————————————————————————————————

●落札カードデザイン

【目的】
LIVE配信中なのか　そうでないのか　の見分けをつきやすくする

・暫定修正事項
ステータス（LIVE配信中など）タグ色のパターン考案
アイテム詳細　という文言の再検討
サムネイル下に、配信中　という表記を追加

**Comment by TAKUOO** [comment]
@mebius-design 
先ほど担当者と話しその場で、一度このようなデザインで提案しています。
UIボードの方にもおいています。
なのですみませんが、先に最高権利者の表示部分をお願いします！
<img width="1399" alt="____________________________2021-04-21_12 20 09" src="https://user-images.githubusercontent.com/39471524/115495164-065b9900-a2a2-11eb-98c9-1263ba2d856d.png">
<img width="1091" alt="____________________________2021-04-21_12 20 22" src="https://user-images.githubusercontent.com/39471524/115495179-0d82a700-a2a2-11eb-822e-a9e0379d14f0.png">

**Comment by mebius-design** [comment]
@TAKUOO 
ご共有頂き、ありがとうございます！承知いたしました。
本件は、一度　最高権利者の表示部分　の作成を進めさせて頂きます。

**Comment by mebius-design** [comment]
@TAKUOO 
最高権利者の表示部分　につきまして
現状の考案を共有させて頂きます。
https://www.figma.com/file/31Vn3nMe45FipnqK5fKUfO/MEKIKI-UI-BOARD?node-id=1%3A146214

最高落札者エリアの表示次第で高さが変わってしまうという
課題解決に加えて

LIVE配信中に、（ユーザー自身が）落札者である事を
即座に認識できる（場合によっては、入札を急いで行う）
上記が達成する事が大切に感じました。

ですので、LIVE配信中は常に
上部に　LIVE配信ステータスのバー　を表示。
そのバーの余白に、落札権利がある、もしくは入札を行える仕組みがあるような
構造を意識しました。

右部の　入札する　は、本構成の場合だと、
フッターの入札エリアへのアンカーリンクを想定しています。

このままだと、LIVE配信中の表記が少し多い気もしますが
もし現時点で気になる点があれば、そのご指摘を踏まえて
明日に調整出来ればと思っていますので、
ご確認の程、よろしくお願いいたします。

<img width="603" alt="ss_0421" src="https://user-images.githubusercontent.com/52993138/115523140-bc85a980-a2c7-11eb-9ef2-4cf3ce027fae.png">

**Comment by TAKUOO** [comment]
@TAKUOO 
ご提案有難うございます！コメントfigma内で書いています。
> 即座に認識できる（場合によっては、入札を急いで行う)

この意図はあってます！
ただフッターではなくブラウザ下部に固定され、すでにすぐに入札ができます。

> LIVE配信中の表記が少し多い気もします

ですね。現状での配信中は、画像部分のみで良いかもですね。
すでにここに訪れるユーザーは、ライブとわかって遷移してると思うので。
LIVEアイテムなどの詳細と区分できれば大丈夫です。
こちらもご提案有難うございます。

**Comment by mebius-design** [comment]
@TAKUOO 
昨日はご確認頂き、ありがとうございます！
Figmaのコメントも拝見しましたので、調整後
再度、ご報告をさせて頂きます。

**Comment by mebius-design** [comment]
@TAKUOO 
お待たせいたしました。本件、調整させて頂きました。
https://www.figma.com/file/31Vn3nMe45FipnqK5fKUfO/MEKIKI-UI-BOARD?node-id=1%3A146214

一点、三つ目に頂いたコメントのみ
確認も兼ねて、ご返信させて頂いておりますので
お手すきの際に、ご確認頂けますと幸いです。

**Comment by TAKUOO** [comment]
@mebius-design 
有難うございます！コメント返答してます。

**Comment by mebius-design** [comment]
@TAKUOO 
先ほどは各所ご確認頂き、ありがとうございます！
再調整させて頂きました。
https://www.figma.com/file/31Vn3nMe45FipnqK5fKUfO/MEKIKI-UI-BOARD?node-id=1%3A146214

恐れ入りますが、この後別件で外出予定なので、
何かあれば、16時〜18時頃を目安にに対応させて頂ければと思います。

**Comment by TAKUOO** [comment]
@TAKUOO 
有難うございます！こちらは完了で大丈夫です！
次はこちらをお願いします。
MEKIKI | ライブオークションカードのUIデザイン #42

**Comment by mebius-design** [comment]
@TAKUOO 
先ほどはご確認頂き、ありがとうございます！
MEKIKI | ライブオークションカードのUIデザイン #42
上記、承知いたしました。
先に確認事項を、該当カードに記載させて頂きます。
