### ISSUE TITLE
MEKIKI | UI デザイン調整

### ISSUE THREAD

**Issue by TAKUOO** [TAKUOO/rubydesign_works#46]
### マイストーンは、今週金曜まで
- [x] ライブの終了タグをグレーベタ(ポップアップカード, ライブ時の入札エリア)
- [x] ポップアップカード修正
- [x] 管理画面のアクションバーデザイン
- [x] ページャーデザイン変更

**Comment by TAKUOO** [comment]
##  ポップアップカードのLIVE中を画像下に
### サムネイル画像は出来るだけ見せたいという事で画像の下に配置。
### ボタンも、押せないという目的を満たせばいいため、ボタンラベルは元に戻す
<img width="991" alt="スクリーンショット 2021-04-27 13 45 38" src="https://user-images.githubusercontent.com/39471524/116186819-55507500-a75f-11eb-9e8f-edf16ed84ebd.png">

**Comment by TAKUOO** [comment]
## 管理画面のアクションバーデザイン
ライブオークション時の運営側の管理パネルで、ライブの操作画面の改修となります。
改修部分は赤枠箇所のアクションバーとなります。
また、現在) 前のアイテム/次のアイテム→ 改修) 前へ/ 次へ に文字数も減らしてください。
<img width="874" alt="スクリーンショット 2021-04-27 13 53 19" src="https://user-images.githubusercontent.com/39471524/116187383-651c8900-a760-11eb-97a6-a452d08dd565.png">

## 変更内容
まずSTE01の「イベント開始」ボタンのみの表示があるバーが表示され、イベント開始を押すと、STEP02の操作するバーが表示されます。そのため、イラストに合わせたデザインにレイアウト変更をお願いします。今回機能群をグルーピングした操作画面が良いのではと話のためで、改修に至りました。

![____________________________2021-04-27_11 42 48](https://user-images.githubusercontent.com/39471524/116188020-99447980-a761-11eb-820e-82c102544157.jpg)

**Comment by TAKUOO** [comment]
## ページャーデザイン変更
### 変更の背景
店舗スタッフで手分けをして画像のチェックをしているのですが、○○さんが3.4ページ目、××さんが9.10ページ目と割り振ってやってます。商品一覧のページでは1.2…24ページという風に画面表示があり、例えば15ページ目を開くのに一つ一つページを選ばないとたどり着けないので不便を感じております。

## 変更内容
現状一覧の頭とお尻にあり、右側にありますが、ページャーだけで1段大きく確保に変更。
また、お尻部分のソートなどの部分は削除してください。
![スクリーンショット 2021-04-27 14 24 05](https://user-images.githubusercontent.com/39471524/116189759-65b71e80-a764-11eb-9da4-a73bf7f8918c.png)
<img width="997" alt="スクリーンショット 2021-04-27 14 20 36" src="https://user-images.githubusercontent.com/39471524/116189775-694aa580-a764-11eb-941e-ee62a0295cd9.png">


### ZOZOのページャーを参考に変更。
### 1. ページ目の表示
<img width="801" alt="スクリーンショット 2021-04-27 14 15 05" src="https://user-images.githubusercontent.com/39471524/116188965-348a1e80-a763-11eb-9ba4-4910af6532b1.png">

### 2. 中盤の表示
<img width="806" alt="スクリーンショット 2021-04-27 14 14 52" src="https://user-images.githubusercontent.com/39471524/116188986-3c49c300-a763-11eb-96b7-d50bab06eb92.png">

### 3. 最後尾での表示
<img width="780" alt="スクリーンショット 2021-04-27 14 15 16" src="https://user-images.githubusercontent.com/39471524/116189003-44a1fe00-a763-11eb-8d8e-bed327c53b0e.png">

**Comment by mebius-design** [comment]
@TAKUOO 
お待たせいたしました。本件の調整、完了しましたので
ご報告させて頂きます。
https://www.figma.com/file/31Vn3nMe45FipnqK5fKUfO/MEKIKI-UI-BOARD?node-id=1%3A146214

場所は、コメントにてピンをしておりますので
ご確認の程、よろしくお願いいたします。

**Comment by TAKUOO** [comment]
@mebius-design 
ありがとうございます！
コメントしています。調整お願いします。

**Comment by mebius-design** [comment]
@TAKUOO 
先ほどはありがとうございます！
頂いたコメント内容、修正いたしましたので
ご確認の程、よろしくお願いいたします。
https://www.figma.com/file/31Vn3nMe45FipnqK5fKUfO/MEKIKI-UI-BOARD?node-id=1%3A146214

**Comment by TAKUOO** [comment]
@mebius-design 
修正有難うございます！
ページャーの仕様はこちらです。もう一度仕様ご確認ください。
## 変更内容
現状一覧の頭とお尻にあり、右側にありますが、ページャーだけで1段大きく確保に変更。
また、お尻部分のソートなどの部分は削除してください。
![スクリーンショット 2021-04-27 14 24 05](https://user-images.githubusercontent.com/39471524/116189759-65b71e80-a764-11eb-9da4-a73bf7f8918c.png)
<img width="997" alt="スクリーンショット 2021-04-27 14 20 36" src="https://user-images.githubusercontent.com/39471524/116189775-694aa580-a764-11eb-941e-ee62a0295cd9.png">
